version: '3.8'

services:
  oauth:
    build: ./oauth
    container_name: oauth
    ports:
      - "8080:8080"
    networks:
      - hubofinnovations-network
    environment:
      - SERVER_PORT=${OAUTH_INTERNAL_PORT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    depends_on:
      - postgres


  innovations:
    build: ./innovations
    container_name: innovations
    ports:
      - "8081:8081"
    networks:
      - hubofinnovations-network
    environment:
      - SERVER_PORT=8081
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-hubdb}
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: hub-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-hubdb}
    networks:
      - hubofinnovations-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  hubofinnovations-network:
    driver: bridge

volumes:
  postgres_data: